<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laporan Sistem Informasi Pertanahan</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #28a745;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #28a745;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table th, table td {
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table th {
            background-color: #28a745;
            color: white;
            font-weight: bold;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Sistem Informasi Pertanahan</h1>
        <p>Data Tanah dan Pemilik Terbaru</p>
        <p>Dicetak pada: {{ date('d-m-Y H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID Tanah</th>
                <th>Nama</th>
                <th>Luas (m²)</th>
                <th>Keterangan</th>
                <th>Warna</th>
                <th>Tanggal Dibuat</th>
            </tr>
        </thead>
        <tbody>
            @foreach($polygons as $polygon)
            <tr>
                <td>{{ $polygon->id }}</td>
                <td>{{ $polygon->nama }}</td>
                <td>{{ number_format($polygon->luas, 2) }}</td>
                <td>{{ $polygon->keterangan ?? '-' }}</td>
                <td>{{ $polygon->warna }}</td>
                <td>{{ $polygon->created_at->format('d-m-Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Data: {{ $polygons->count() }} tanah</p>
        <p>Sistem Informasi Pertanahan - Generated by Laravel</p>
    </div>
</body>
